[package]
name = "calcutron"
version = "0.1.0"
edition = "2024"
authors = ["Calcutron Contributors"]
description = "A Reverse Polish Notation (RPN) calculator implemented in Rust with Iced GUI"
repository = "https://github.com/yourusername/calcutron"
license = "MIT"
keywords = ["calculator", "rpn", "gui", "iced"]
categories = ["gui"]

[dependencies]
iced = { version = "0.13.1", features = ["svg"] }